version: "3.0"

services:
  db:
    image: mysql:8.0.28
    container_name: busybox
    ports:
      - "33061:3306"
    command: --init-file /data/scripts/init.sql
    volumes:
      - ./scripts/:/data/scripts/
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: department_service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
